// Generated by CoffeeScript 1.3.3

describe("nanoScroller", function() {
  var $content, $nano, $pane, $slider;
  $nano = null;
  $content = null;
  $pane = null;
  $slider = null;
  jasmine.getFixtures().fixturesPath = 'spec/fixtures';
  return describe("when the plugin is called without any options", function() {
    beforeEach(function() {
      loadFixtures('nano.html');
      $nano = $("#nano");
      return $nano.nanoScroller();
    });
    describe("content element", function() {
      beforeEach(function() {
        return $content = $nano.find('.content');
      });
      it("should exist", function() {
        expect($content).toExist();
        expect($content.length).toBeTruthy();
        return expect($nano).toContain("div.content");
      });
      return it("should have tabindex attribute set", function() {
        return expect($content).toHaveAttr('tabindex');
      });
    });
    describe("pane element", function() {
      beforeEach(function() {
        return $pane = $nano.find('.pane');
      });
      return it("should exist", function() {
        expect($pane).toExist();
        expect($pane.length).toBeTruthy();
        return expect($nano).toContain("div.pane");
      });
    });
    return describe("slider element", function() {
      beforeEach(function() {
        return $slider = $nano.find('.slider');
      });
      it("should exist", function() {
        expect($slider).toExist();
        expect($slider.length).toBeTruthy();
        return expect($nano).toContain("div.slider");
      });
      return it("should have style attribute set", function() {
        return expect($slider).toHaveAttr('style');
      });
    });
  });
});
